[package]
name = "web_auth"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
kube = { version = "0.99", features = ["runtime", "client", "derive"] }
k8s-openapi = { version = "0.24", features = ["latest"] }
rmcp = { version = "0.16", features = ["server", "transport-io"] }
anyhow = "1.0"
futures = "0.3"
hickory-resolver = "0.25"
bytes = "1"
http = "1"
http-body-util = "0.1"
hyper = "1"
hyper-util = { version = "0.1", features = ["client-legacy", "http1", "http2", "tokio"] }
hyper-rustls = { version = "0.27", features = ["http1", "http2", "native-tokio", "tls12"] }
tokio-rustls = "0.26"